{{- if .Values.stack.hook.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-hook
  namespace: {{ .Release.Namespace }}
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download the Hook artifacts.
    apt-get update
    apt-get install -y wget
    set -euxo pipefail
    cd /output
    rm -f *.tar.gz checksum.txt vmlinuz* initramfs*
    base_loc="{{ .Values.stack.hook.downloadURL }}"
    files="$base_loc/hook_aarch64.tar.gz $base_loc/hook_x86_64.tar.gz $base_loc/checksum.txt"
    tmp_dir=$(mktemp -d)
    for f in ${files}; do
      echo "${f}"
      wget -P "${tmp_dir}" "${f}"
    done
    (cd "${tmp_dir}" && sha512sum -c checksum.txt)
    mv "${tmp_dir}"/checksum.txt .
    for f in ${tmp_dir}/*.tar.gz; do tar --no-same-permissions --overwrite -ozxvf "${f}" && rm -f "${f}"; done
    rm -rf "${tmp_dir}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-hook
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 50
  template:
    metadata:
      labels:
        app: download-hook
    spec:
      containers:
        - name: download-hook
          image: {{ .Values.stack.hook.image }}
          command: ["/script/entrypoint.sh"]
          env:
            - name: http_proxy
              value: http://proxy-dmz.intel.com:911
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: no_proxy
              value: localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.svc.cluster.local,cdi-api,localhost,virt-api,*.intel.com,*intel.com,/var/run/docker.sock,/run/containerd/containerd.sock,172.22.32.0/22,172.22.33.51,172.22.33.237  
            - name: HTTP_PROXY 
              value: http://proxy-dmz.intel.com:911 
            - name: HTTPS_PROXY 
              value: http://proxy-dmz.intel.com:912
            - name: NO_PROXY 
              value: localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.svc.cluster.local,cdi-api,localhost,virt-api,*.intel.com,*intel.com,/var/run/docker.sock,/run/containerd/containerd.sock,172.22.32.0/22,172.22.33.51,172.22.33.237
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        - name: hook-artifacts
          hostPath:
            path: {{ .Values.stack.hook.downloadsDest }}
            type: DirectoryOrCreate
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-hook
{{- end }}